name: dockgraph

services:
  dockgraph:
    build: .
    ports:
      - "7800:7800"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-compose.yml:/app/compose/docker-compose.yml:ro
      - ./demo/docker-compose.yml:/app/compose/demo.yml:ro
                    labels:
      dev.dockgraph.self: "true"
